### ISSUE TITLE
Promise instanceof fails

### ISSUE THREAD

**Issue by ghost** [jrimclean/remoting.io#1]
I verified that my invoked function returns a Promise but in handlers.js the instanceof check fails. I'm using the same es6-promises library but requiring it from my own node_modules directory. What could I do differently? Also is using Promises a rewuirement?

**Comment by empyreanx** [comment]
I'll have a look at it. What version of NodeJS/io.js and es6-promises are you using? Returning a promise from an exported method is only necessary if the method performs any asynchronous operations (such as reading from a database).

**Comment by ghost** [comment]
To get things working I just did this:
var Promise = require('remoting.io/node_modules/es6-promise').Promise;
instead of this:
var Promise = require('es6-promise').Promise; // was a separate package
installation

node: v0.10.32
es6-promise: 2.0.1

**Comment by empyreanx** [comment]
According to your test, the 'returned instanceof Promise' line is only checking it against the bundled Promise implementation, a silly oversight on my part. I plan to replace this with support for any 'thenable' object. Expect a new version by week's end. Thanks for bringing this to my attention.

**Comment by empyreanx** [comment]
Actually I found the inspiration to tackle this today. The latest version is published. See if it solves your problem.

**Comment by ghost** [comment]
I haven't downloaded the patch yet - thanks for doing it. I'll try to get on it in a few minutes. This project is really nice work. It's simple and the code looks neat. So many of the other RPC and JSON-RPC libs and WAMP, etc are way too complicated. e.g. keep it simple. Excellent work. At some point I'll probably be looking for bi-directional RPC maybe later on.

**Comment by empyreanx** [comment]
Thanks for the praise, it's always appreciated. I'm going to mark this issue as closed, but if you have any other problems I'd be more than happy to help out.
